### ISSUE TITLE
Memory Corruption on MacOS

### ISSUE THREAD

**Issue by GagaLP** [nikolausrauch/2D-viewer#1]
In your demo, there's a code passage at

https://github.com/nikolausrauch/2D-viewer/blob/9bb50680352b1918aeda54553c558f59555ea44e/demo/demo.cpp#L71-L77

When executed on a MacBook (with an M1 processor), it leads to the following error:

```code
demo(55959,0x1dc8fd000) malloc: Incorrect checksum for freed object 0x14a608310: probably modified after being freed.
Corrupt value: 0x343bbd2e3f800000
demo(55959,0x1dc8fd000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    55959 abort      ./bin/demo
```

It appears that the initialization of the new vector (`vertices`) in this function is broken on MacOS. Specifically, referring to 

https://github.com/nikolausrauch/2D-viewer/blob/9bb50680352b1918aeda54553c558f59555ea44e/viewer/viewer.inl#L50-L58

There could be two (or more) ways (for now) to fix this:

You could do something like:
```c++
#ifndef __APPLE__
std::vector<glm::vec2> vertices(mRender.circleVertices);
for (unsigned int i = 0; i <= mRender.circleVertices; i++) {
    vertices[i] = {
        radius * glm::cos(2.0 * glm::pi<float>() * static_cast<float>(i) / mRender.circleVertices),
        radius * glm::sin(2.0 * glm::pi<float>() * static_cast<float>(i) / mRender.circleVertices)};
}
#endif

...

for (unsigned int i = 0; i <= mRender.circleVertices; i++) {
#ifdef __APPLE__
    glVertex2f(position.x + radius * radius * glm::cos(2.0 * glm::pi<float>() * static_cast<float>(i) / mRender.circleVertices),
                       position.y + radius * radius * glm::sin(2.0 * glm::pi<float>() * static_cast<float>(i) / mRender.circleVertices));
#else
    glVertex2f(position.x + radius * vertices[i].x,
                       position.y + radius * vertices[i].y);
#endif
}
```

Or, without the `#ifdef`:

```c++
...
for (unsigned int i = 0; i <= mRender.circleVertices; i++) {
    const float angle = 2.0 * glm::pi<float>() * static_cast<float>(i) / mRender.circleVertices;  // For readability purposes
    glVertex2f(position.x + radius * radius * glm::cos(angle),
                       position.y + radius * radius * glm::sin(angle));
}
```

As you mentioned, you're not exactly sure why this happens, but with these changes, it wouldn't occur anymore. Additionally, you questioned why the `vertices` array is used in the first place, since, from your understanding, these vertices are only used once.

**Comment by nikolausrauch** [comment]
Thank you for finding this.
This is not an Apple related bug though -- it's just an out-of-bounds access to `vertices` ?

**Comment by GagaLP** [comment]
You're completely right. I don't think I was fully awake last night. XD I saw you fixed it, and it works now without any errors. Nice!
